Example token auth
apiflask/apiflask pull request #266
Opened 2022-05-04 07:14 UTC by z-t-y

Finishes the first item in #262 

Checklist:

- [ ] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the `docs` folder and in code docstring.
- [ ] Add an entry in `CHANGES.md` summarizing the change and linking to the issue and your username.
- [ ] Add `*Version changed*` or `*Version added*` note in any relevant docs and docstring.
- [ ] Run `pytest` and `tox`, no tests failed.

2022-05-04 08:12 UTC, greyli commented
Thanks for working on this! I will review it later.

2022-05-05 01:42 UTC, greyli requested changes

2022-05-05 01:42 UTC, greyli commented on examples/auth/token_auth/app.py
> +    except BaseException:
Using `authlib.jose.JoseError` will be more appropriate.

2022-05-05 01:42 UTC, greyli commented on examples/auth/token_auth/app.py
> +    g.current_user = user
Just return the user, then get the current user in the view function with `auth.current_user`.

2022-05-05 01:42 UTC, greyli commented on requirements/examples.txt
> -importlib-metadata==4.11.3
Keep this item and the `zipp` for users with Python < 3.8.

2022-05-05 01:42 UTC, greyli commented on examples/auth/token_auth/app.py
> +    if isinstance(g.current_user, User):
This if statement seems unnecessary (?).

2022-05-05 01:42 UTC, greyli commented on examples/auth/token_auth/app.py
> +def get_token(id: int):
It's better to set up a `TokenSchema` with `app.output`.

2022-05-05 04:03 UTC, z-t-y commented
@greyli Changes have been made according to the reviews.

2022-05-08 09:08 UTC, greyli approved these changes

2022-05-08 09:09 UTC, merged

2022-05-08 09:09 UTC, greyli commented
Thanks!