for compat with flask 2.2
apiflask/apiflask pull request #343
Opened 2022-08-23 02:48 UTC by hjlarry

1. In flask2.2,  use `_request_ctx_stack` will cause a warning, and it will be removed in flask2.3
2. In flask2.2, some unit test will raise [AssertionError](https://github.com/pallets/flask/blob/main/src/flask/app.py#L720). I try to mofidy the route order to fix this

some other unittest of flask2.2 can't pass is caused by the [class-based views issue](https://github.com/apiflask/apiflask/issues/341).

Checklist:

- [X] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the `docs` folder and in code docstring.
- [ ] Add an entry in `CHANGES.md` summarizing the change and linking to the issue and your username.
- [ ] Add `*Version changed*` or `*Version added*` note in any relevant docs and docstring.
- [X] Run `pytest` and `tox`, no tests failed.

2022-08-23 08:23 UTC, mmdbalkhi requested changes
Imo we should ignore the type here.

2022-08-23 08:24 UTC, mmdbalkhi requested changes

2022-08-23 08:24 UTC, mmdbalkhi commented on src/apiflask/app.py
> +    request_ctx = None
Imo we should ignore the type here.

```suggestion
    request_ctx = None  # type: ignore
```

2022-08-24 04:05 UTC, merged

2022-08-24 04:16 UTC, greyli commented
@hjlarry @mmdbalkhi Thanks! 

For the CBV issue, I'm thinking of patching the class view in the [`add_url_rule`](https://github.com/apiflask/apiflask/blob/main/src/apiflask/route.py#L62), but I'm not sure how to modify the function to accept positional args. Otherwise, we may need to copy Flask's view module to this function.

In 2.0, we could consider passing all args as keyword args ([ref](https://github.com/pallets/flask/pull/4776#issuecomment-1222529526)).