Loosen flask version requirement to >= 2
apiflask/apiflask pull request #479
Opened 2023-09-11 12:58 UTC by wlach

Later versions in the Flask 2.x series changed the API a fair bit.
Loosen the version requirement to >= 2, which allows people to continue
using 2.0.x and 2.1.x. Add tests using 2.0.3 to be sure this continues
working. Fixes #478.

2023-09-11 14:44 UTC, wlach commented
There's a fair number of unit test failures because the examples depend on more recent features in flask-sqlalchemy (get_or_404, paginate). I could fix them, but I'd like to wait for guidance from @greyli before continuing.

2023-09-12 14:36 UTC, greyli commented
It's unnecessary to add a separate test env for Flask 2.0.

2023-09-15 15:37 UTC, wlach commented
@greyli Ok I think this is ready for review! Appreciate your support and encouragement on this

2023-09-17 03:44 UTC, greyli requested changes

2023-09-17 03:44 UTC, greyli commented on requirements/flask20.in
> +authlib==1.2.1
The purpose of the flask20 test is to test the minimum versions of the install requirements, so this file should include the following definition:

```
# minimum install requirements
flask==2.0.0
flask-marshmallow==0.12.0
webargs==8.3.0
flask-httpauth==4.0.0
apispec==6.0.0

# for example applications
flask-sqlalchemy==2.5.1
sqlalchemy==1.4.49
marshmallow-dataclass==8.5.0
authlib==1.2.1
```

And the name `min` (for test env, requirement file, etc.) would be more appropriate.

2023-09-18 14:51 UTC, wlach commented on requirements/flask20.in
> +authlib==1.2.1
That makes sense. I think I'll use the name `min-versions` since `min` might be confused with the existing `minimal`

2023-09-18 15:38 UTC, wlach commented on tests/test_openapi_tags.py
> +                    reason='Depends on new behaviour introduced in Flask 2.0.1')
Needed to add these skips as well if we're going to test with actual flask 2.0.0

2023-09-18 15:39 UTC, wlach commented
@greyli ready for another look!

2023-09-19 14:20 UTC, greyli approved these changes
LGTM

2023-09-19 14:21 UTC, merged