Reuse the File, Config field, and file-related validators from flask-marshmallow
apiflask/apiflask pull request #543
Opened 2024-02-18 12:17 UTC by uncle-lv

This pr is for #540 .

2024-02-18 12:38 UTC, uncle-lv commented
I don't know what the file [min-versions.in](https://github.com/apiflask/apiflask/blob/f62ec12b8214b23495dc7cba56ee410a263753c9/requirements/min-versions.in#L3) does. But if I pin flask-marshmallow to 1.0.0 version, I get an error.
```
ERROR! requirements/min-versions.txt was not regenerated after changes in requirements/min-versions.in.
Expecting: # SHA1:3725672cc8aa4cdcab4174d189f19e8bb3ac2b62
Found:     # SHA1:a74d3671a740ec5c076a37aaaa3409fd78f9bde2
```

2024-02-19 13:28 UTC, greyli commented
> I don't know what the file [min-versions.in](https://github.com/apiflask/apiflask/blob/f62ec12b8214b23495dc7cba56ee410a263753c9/requirements/min-versions.in#L3) does. But if I pin flask-marshmallow to 1.0.0 version, I get an error.
> 
> ```
> ERROR! requirements/min-versions.txt was not regenerated after changes in requirements/min-versions.in.
> Expecting: # SHA1:3725672cc8aa4cdcab4174d189f19e8bb3ac2b62
> Found:     # SHA1:a74d3671a740ec5c076a37aaaa3409fd78f9bde2
> ```

The `min-versions.in` file (input) contains the minimal supported version of the dependencies. You could update the version in it, then use `pip-compile-multi` or `pip-compile requirements/min-versions.in` command to generate the `min-versions.txt` file (output, lock file).

Ref:

* https://github.com/jazzband/pip-tools
* https://github.com/peterdemin/pip-compile-multi

2024-02-20 14:05 UTC, greyli requested changes

2024-02-20 14:05 UTC, greyli commented on tests/test_helpers.py
> -    assert 'prev_num' not in rv.json
This file should be kept as it contains the tests for existing helper functions.

2024-02-20 14:05 UTC, greyli commented on CHANGES.md
> + [issue_540]: https://github.com/apiflask/apiflask/issues/540
There are some unnecessary whitespaces here.

```suggestion
- Reuse the File, Config field, and file-related validators from flask-marshmallow ([issue #540][issue_540]).

[issue_540]: https://github.com/apiflask/apiflask/issues/540
```

2024-02-22 00:47 UTC, greyli approved these changes

2024-02-22 00:47 UTC, merged

2024-02-22 00:47 UTC, greyli commented
Thanks!